<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SyncIonicons extends Command
{
    protected $signature = 'ionicons:sync';

    protected $description = 'Generate the Ionicons PHP data file from node_modules for use in the x-ionicon Blade component';

    public function handle(): int
    {
        $ioniconsDir = base_path('node_modules/ionicons/dist/svg');

        if (! is_dir($ioniconsDir)) {
            $this->error('ionicons npm package not found. Run: npm install ionicons');

            return self::FAILURE;
        }

        $files = glob($ioniconsDir.'/*.svg');

        if (empty($files)) {
            $this->error("No SVG files found in {$ioniconsDir}");

            return self::FAILURE;
        }

        $data = [];

        foreach ($files as $file) {
            $name = basename($file, '.svg');
            $svg = file_get_contents($file);

            if (preg_match('/<svg[^>]*>(.*?)<\/svg>/s', $svg, $matches)) {
                $data[$name] = trim($matches[1]);
            }
        }

        ksort($data);

        $outputDir = resource_path('ionicons');
        File::ensureDirectoryExists($outputDir);

        $php = "<?php\n\n// Auto-generated by `php artisan ionicons:sync` — do not edit manually.\n// Re-run the command after updating the ionicons npm package.\n\nreturn ".var_export($data, true).";\n";

        File::put($outputDir.'/data.php', $php);

        $this->info('Ionicons data file generated at resources/ionicons/data.php ('.count($data).' icons total)');

        return self::SUCCESS;
    }
}
