<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SyncHeroicons extends Command
{
    protected $signature = 'heroicons:sync';

    protected $description = 'Generate the Heroicons PHP data file from node_modules for use in the x-heroicon Blade component';

    /** @var array<string, string> */
    private const VARIANT_PATHS = [
        'outline' => '24/outline',
        'solid' => '24/solid',
        'mini' => '20/solid',
        'micro' => '16/solid',
    ];

    public function handle(): int
    {
        $heroiconsDir = base_path('node_modules/heroicons');

        if (! is_dir($heroiconsDir)) {
            $this->error('heroicons npm package not found. Run: npm install heroicons');

            return self::FAILURE;
        }

        $data = [];

        foreach (self::VARIANT_PATHS as $variant => $path) {
            $dir = $heroiconsDir.'/'.$path;
            $files = glob($dir.'/*.svg');

            if (empty($files)) {
                $this->warn("No SVG files found in {$dir}");

                continue;
            }

            $data[$variant] = [];

            foreach ($files as $file) {
                $name = basename($file, '.svg');
                $svg = file_get_contents($file);

                if (preg_match('/<svg[^>]*>(.*?)<\/svg>/s', $svg, $matches)) {
                    $data[$variant][$name] = trim($matches[1]);
                }
            }

            ksort($data[$variant]);
            $this->line("  <fg=green>✓</> {$variant}: ".count($data[$variant]).' icons');
        }

        $outputDir = resource_path('heroicons');
        File::ensureDirectoryExists($outputDir);

        $php = "<?php\n\n// Auto-generated by `php artisan heroicons:sync` — do not edit manually.\n// Re-run the command after updating the heroicons npm package.\n\nreturn ".var_export($data, true).";\n";

        File::put($outputDir.'/data.php', $php);

        $total = array_sum(array_map('count', $data));
        $this->info("Heroicons data file generated at resources/heroicons/data.php ({$total} icons total)");

        return self::SUCCESS;
    }
}
